def generate_explanation(
    prediction,
    ai_probability
):

    score_phrase = (
        "very high" if ai_probability > 80 else
        "moderate" if ai_probability > 50 else
        "low"
    )

    return (
        f"The system assessed this content as {prediction} with {ai_probability}% AI probability. "
        f"This indicates a {score_phrase} chance that the content was generated by AI based on the model's analysis."
    )

# =========================================
# TEST
# =========================================

if __name__ == "__main__":

    response = generate_explanation(
        "AI Generated Text",
        87
    )

    print(response)